security:
  jwt:
    token:
      secret-key: kudu41r0
      expire-length: 3600000
spring:
  datasource:
    url: jdbc:postgresql://kesavan.db.elephantsql.com/qxhuuhqf
    username: qxhuuhqf
    password: AACJ9_93CI_wkp4oho4d5lCC8_w-UbtM
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
springdoc:
  pathsToMatch:
  - /api/**
  - /auth/**
  swagger-ui:
    use-root-path: true




