security:
  jwt:
    token:
      secret-key: kudu41r0
      expire-length: 3600000
spring:
  datasource:
    url: jdbc:postgresql://dpg-cmtkigen7f5s73aq88e0-a.oregon-postgres.render.com/db_inclockgnito_7t5w
    username: db_inclockgnito_7t5w_user
    password: xrOsWO14G3afAuHMVF66mczKm6vnIOpt
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
springdoc:
  pathsToMatch:
  - /api/**
  - /auth/**
  swagger-ui:
    use-root-path: true




